Creating cookie from url parameter
pkoltermann/timecop-bundle pull request #1
Opened 2016-10-27 11:27 UTC by sstaniak

2016-11-01 21:20 UTC, pkoltermann requested changes

2016-11-01 21:20 UTC, pkoltermann commented on src/Kolemp/TimecopBundle/Service/RequestBasedTimeGenerator.php
> +        $fakeTime = $request->attributes->get(static::COOKIE_NAME);
Can't you just get fakeTime from the request directly?

2016-12-01 13:43 UTC, gpkoltermann approved these changes

2016-12-01 13:44 UTC, pkoltermann approved these changes

2016-12-01 13:44 UTC, merged